# Generated by Django 4.2.20 on 2025-08-05 07:42

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("addon_service", "0016_externallinkservice_int_supported_features_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalservice",
            name="icon_name",
            field=models.CharField(
                blank=True,
                help_text="Relative path to icon file within configured icon directories",
                max_length=255,
                null=True,
            ),
        ),
    ]
