# Generated by Django 4.2.20 on 2025-09-07 18:43

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("addon_service", "0017_change_icon_name_to_charfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalstorageservice",
            name="host_info",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
