# Generated by Django 4.2.26 on 2026-02-07 18:25

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("addon_service", "0018_alter_externalservice_icon_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalstorageservice",
            name="host_info",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
